
apiVersion: v1
kind: Namespace
metadata:
  name: cicd
---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: jenkins
  namespace: cicd
---

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: cicd
  name: jenkins-deployer
rules:
  - apiGroups: [""]
    resources: ["pods", "services", "secrets"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: ["apps"]
    resources: ["deployments", "replicasets"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: jenkins-deployer-binding
  namespace: cicd
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: jenkins-deployer
subjects:
  - kind: ServiceAccount
    name: jenkins
    namespace: cicd
---

apiVersion: v1
kind: Secret
metadata:
  name: jenkins-sa-token
  namespace: cicd
  annotations:
    kubernetes.io/service-account.name: jenkins
type: kubernetes.io/service-account-token
---

